settings:
  #################   DATASET CONFIG   ###################

  trainloader:
    name: NumpyFeatureLoader
    args:
      root_dir: "/Users/rishideychowdhury/Desktop/Joint-Embedding/Data/flickr30k_images/flickr30k_images/flickr30k_images"
      ann_path: "/Users/rishideychowdhury/Desktop/Joint-Embedding/Data/flickr30k_annotations/train.json"
      feat_dir: "/Users/rishideychowdhury/Desktop/Joint-Embedding/Data/bottom_up"
      text_dir: "/Users/rishideychowdhury/Desktop/Joint-Embedding/Data/bert_features"
      batch_size: 128
      num_workers: 2

  valloader:
    name: RawNumpyFeatureLoader
    args:
      root_dir: "/Users/rishideychowdhury/Desktop/Joint-Embedding/Data/flickr30k_images/flickr30k_images/flickr30k_images"
      ann_path: "/Users/rishideychowdhury/Desktop/Joint-Embedding/Data/flickr30k_annotations/val.json"
      feat_dir: "/Users/rishideychowdhury/Desktop/Joint-Embedding/Data/bottom_up"
      text_dir: "/Users/rishideychowdhury/Desktop/Joint-Embedding/Data/bert_features"
      batch_size: 128
      num_workers: 2

  ## Those dataset for metric evaluation
  valset1:
    name: BottomUpSet
    args:
      feat_dir: "/Users/rishideychowdhury/Desktop/Joint-Embedding/Data/bottom_up"
      ann_path: "/Users/rishideychowdhury/Desktop/Joint-Embedding/Data/flickr30k_annotations/val.json"
      
  valset2:
    name: BertSet
    args:
      feat_dir: "/Users/rishideychowdhury/Desktop/Joint-Embedding/Data/bert_features"
      ann_path: "/Users/rishideychowdhury/Desktop/Joint-Embedding/Data/flickr30k_annotations/val.json"

  #################   TRAINING CONFIG   ###################
  
  globals:
    gpu_devices: ''                     # supports multi-gpus -- PREVIOUSLY WAS SET TO '0'
    num_epochs: 100                       # Previously 100 ------ LOOOOOK
    mixed_precision: False                # whether to use nvidia apex
    total_accumulate_steps: 0           # step * batch_size, not use if equal 0, gradient accumulation
  
  model:
    name: "TERN"
    args:
      d_embed: 1024                      # output_dim
      d_model: 768                       # model dim
      d_ff: 2048                         # feed-forward dim
      aggregation: "mean"               # [mean, first]
      N_v: 4                             # number of layers
      N_l: 0                             # number of layers
      heads: 4                           # number of heads
      dropout: 0.1
      precomp_bert: True                # whether to use bert feature extractor
      num_sw_layers: 0                       #number of shared-weight layer


  loss:
    name: "contrastive_tern"                # [contrastive, contrastive_tern, nxtent, custom_nxtent, triplet] # PREVIOUSLY "contrastive"
    # distance: 
    #   name: "cosine"                   # [cosine, dot, euclidean]      
    # reducer:
    #   name: "threshold"
    #   high: 0.2
    # regularizer:                     # [l1, l2, mean]
    #   name: "l2"
      
  # learning rate policy
  lr_policy:
    name: "adam"                         #[adam|sgd]
    lr: 0.001                            #[adam: 1e-3 | sgd: 1e-2]
    momentum: 0.937
    weight_decay: 0.0005

  lr_scheduler:
    name: "cosine2"                      #[plateau | cosine | 1cycle-yolo | 1cycle]
                                        # if need to specify more scheduler arguments, do it here

